### PR TITLE
Try a header font

### PR DESCRIPTION
**Pull request by golmansax**

### CODE REVIEW

**Comment by judymou** [comment]
can you include a screenshot?

**Comment by golmansax** [comment]
captura de pantalla 2015-09-03 a las 2 59 36 pm

trying to get it a more professional edge.  thoughts?

**Comment by judymou** [comment]
hmm i prefer the previous one slightly. This reminds me of collegeboard.com

**Comment by golmansax** [comment]
k so you prefer less professional, more friendly?

**Comment by judymou** [comment]
yeah this is a very friendly site, but could be convinced otherwise

**Comment by golmansax** [comment]
k second try.  i kept the same font but made the text thinner to have a bit more contrast.
captura de pantalla 2015-09-03 a las 3 25 11 pm

**Comment by judymou** [comment]
looks great thanks!

**Pull request merged**
